#!/usr/bin/env bash
#
# *****
# This example was taken from the book "Mastering UNIX Shell Scripting"
# 2nd Edition, by Randy K. Michael; therefore He is the intellectual master
# and all the credits are attributed to him. You can see more about his book in:
#
#                   https://www.wiley.com/go/michael2e
#
# Copyright © 2008 by Randal K. Michael
# Published by Wiley Publishing, Inc., Indianapolis, Indiana
# Published simultaneously in Canada
# ISBN: 978-0-470-18301-4
# *****
#
# #############################
#
# SCRIPT: NAME_of_SCRIPT
# AUTHOR: AUTHORS_NAME
# DATE:   DATE_of_CREATION
# REV:    1.1.A (Valid are A, B, D, T, Q, and P)
#               (For Alpha, Beta, Dev, Test, QA, and Production)
#
# PLATFORM: Solaris
#
#
# REQUIREMENTS: Setup the correct "awk" usage. Solaris needs to
#               use "nawk" instead of "awk"
#
#         EXAMPLE:  case $(uname) in
#                   SunOS) alias awk=nawk
#                          ;;
#                   esac
#
# PURPOSE: Give a clear, and if necessary, long, description of the
#          purpose of the shell script. This will also help you stay
#          focused on the task at hand.
#
# REV LIST:
#        DATE: DATE_of_REVISION
#        BY:   AUTHOR_of_MODIFICATION
#        MODIFICATION: Describe what was modified, new features, etc--
#
#
# set -n   # Uncomment to check script syntax, without execution.
#          # NOTE: Do not forget to put the # comment back in or
#          #       the shell script will never execute!
# set -x   # Uncomment to debug this shell script
#
##########################################################
#         DEFINE FILES AND VARIABLES HERE
##########################################################

##########################################################
#              DEFINE FUNCTIONS HERE
##########################################################

##########################################################
#               BEGINNING OF MAIN
##########################################################

# End of script
